import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/app/contexts/AppProvider";
import { cookies } from "next/headers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = cookies();
	const sessionToken = cookieStore.get("sessionToken");

	return (
		<>
			<html lang="en" suppressHydrationWarning={true}>
				<body className={inter.className}>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
						<AppProvider inititalSessionToken={sessionToken?.value as string}>
							<Header />
							{children}
						</AppProvider>
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</>
	);
}
